// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_stories_ from "./routes/[...stories].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $stories_id_ from "./routes/stories/[id].tsx";
import * as $Comment from "./islands/Comment.tsx";
import * as $Toggle from "./islands/Toggle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...stories].tsx": $_stories_,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/stories/[id].tsx": $stories_id_,
  },
  islands: {
    "./islands/Comment.tsx": $Comment,
    "./islands/Toggle.tsx": $Toggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
